dist: trusty
language: java

jdk:
  - openjdk11

# the first part of the cache phase happens
# between git checkout and before_install
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - cp ./settings.xml $HOME/.m2/settings.xml

# the default java install step does
# mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install:
  - mvn install -DskipTests=true -B -V

# addons are executed between install and script
addons:
  sonarcloud:
    organization: "vainyksi"
    token:
      secure: "TuNK7Ma81KN2FLBA4ZZIhe2XD3FCkxndsCMYyOj6tirWRyUJFT8Pwyz32c4xP6GizLQkqJWE07bvqVkJL6wVYEVdYmcVE15Q0XyA+4EEy3C4bgA3bn8Klw8bCoDwxk6Owe3bD1Zg963r+t5xVWDn1eymd25M2fEoDgAyQ44V2d/2yyegl15oF0tTNYptqDxSyijx67KZXq8g2ARMICxRvyc6pvpihkjlOokVnSgL+SB4EAVZBHWUVL7uB2d9dSKDEoNF7VoSluiN/sGnfu1BBA9RQXAKRE4awO7e63SbR9yvtbPBxjVWqltc8EYl6Txs8txImcJlvzVPlvlgtgFTywxjdsG7bThh7zBbOF6fuhPqPiJiEaskddWWzHMPogVbn517AmBpASy6w8iGmt7nMDd7at0xHNZPnjPZf2LN1K6hKavdBl8o7c5u+o9wQytTjdN6jQtSEq3TeDcC6JR7f5d4dGbmMrDfXqZ26Cj6FAcRN0RxnW6nqhyWvpsrwuFXYAffDf06QyLTGIfWjeclGjv5zAkFgMIJ/sidp46i4udiPGEs/qkrI8yR354lxMxcHZBFpAc2Aaj4tbSkKwt/simbsmU0NhLx/miNPrNgqsLFs0fuvKaE94N0o9C+w0jBzWT9tbbkOWYkweRuM8XNi8qrWpmmMoO+G+BEql+s2c8="

# splitting the build into install and test parts gives us a quicker way
# to identify what went wrong
script:
  - mvn test -B
#  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn sonar:sonar -Dsonar.projectKey=PantheonTechnologies_lighty-core -Dsonar.host.url=https://sonarcloud.io; fi
#  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then mvn sonar:sonar -Dsonar.projectKey=vainyksi_lighty-core-coverity1 -Dsonar.host.url=https://sonarcloud.io; fi
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=vainyksi_lighty-core-coverity1


# before_cache happens before the second part of the cache phase,
# which happens after script
before_cache:
  - rm -rf $HOME/.m2/repository/io/lighty
